spring:
  rabbitmq:
    host: 192.168.1.110
    port: 5672
    listener:
      direct:
        consumers-per-queue: 1
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 5
        max-concurrency: 5
    virtual-host: /
    connection-timeout: 5000
    publisher-confirm-type: correlated